### ISSUE TITLE
Global Cache IP2CC bugs

### ISSUE THREAD

**Issue by jficklin-tpcc** [bitfocus/companion-module-globalcache-itac-cc#3]
I just imported the presets for the Global Cache IP2CC module that I own.  I am really excited to use this with StreamDeck.  However, the presets do random button presses of other buttons on my StreamDeck after pushing.

**Comment by cxselph** [comment]
Could you tell us a little more about your setup? Version of Companion. Are you running the streamdeck app at the same time? If so, you can’t currently run it at the same time with 2.0. Are you able to manually setup buttons without presets without issues? The random button presses sound more like a faulty streamdeck. Just trying to narrow down the possibilities. You can also test with the emulator in the browser to possibly rule out an issue with faulty streamdeck. Let me know. I can pull out my ip2cc tomorrow and see if I run into similar issues. I haven't used it since 1.3.

**Comment by jficklin-tpcc** [comment]
Morning –

Companion I’m running on PC is v1.4.0 (backport-b402e70-1559).

No, I am not running any StreamDeck software alongside with Companion.

I can set up buttons manually, however, the problem still exists.

When using the emulator, the problem does NOT occur.

I borrowed another StreamDeck XL we had on-hand, and had NO issues.

After speaking to our director that purchased the StreamDecks for us, he did tell me that there was one StreamDeck that was giving him fits with random button pushes.  Guess I found that one.

I will connect with StreamDeck if they can work with me on a replacement hardware.

Thanks !!
-jf

**Comment by cxselph** [comment]
I’m glad you got it worked out.

**Comment by JeffreyDavidsz** [comment]
To be clear 1.4 does not support XL and the newer standard streamdeck. If it works you are just lucky. See also facebook post

**Comment by jficklin-tpcc** [comment]
You are correct.  I had to download a v2.0 version for it to work with XL.  We use XL in our Mac environment and was aware of that when troubleshooting.
